### PR TITLE
stand alone npm pkg

### PR DESCRIPTION
**Pull request by Laksh47**
Refs: https://medium.com/better-programming/create-and-publish-your-npm-package-node-module-in-just-10-minutes-4b91e30fe9d7

### CODE REVIEW

**Comment by Laksh47** [comment]
```
➜  timebomb git:(stand_alone_npm_pkg) ✗ sudo npm install -g .
/usr/local/bin/timebomb -> /usr/local/lib/node_modules/timebomb/index.js
+ timebomb@0.1.0
updated 1 package in 0.067s
➜  timebomb git:(stand_alone_npm_pkg) ✗ timebomb
➜  timebomb git:(stand_alone_npm_pkg) ✗ timebomb testing
testing
➜  timebomb git:(stand_alone_npm_pkg) ✗ sudo npm uninstall -g timebomb
removed 1 package in 0.053s
➜  timebomb git:(stand_alone_npm_pkg) ✗ 
```


@123aswin123 @shivasurya

**Comment by shivasurya** [comment]
LGTM

**Comment by shivasurya** [comment]
@Laksh47 bro check this na https://github.com/marketplace/actions/publish-to-npm

**Comment by Laksh47** [comment]
Will do @shivasurya

**Comment by Laksh47** [comment]
```
➜  vedi git:(stand_alone_npm_pkg) ✗ sudo npm install -g .     
/usr/local/bin/vedi -> /usr/local/lib/node_modules/vedi/index.js
+ vedi@0.1.0
added 1 package in 0.069s
➜  vedi git:(stand_alone_npm_pkg) ✗ vedi aswin is a genius
aswin
is
a
genius
➜  vedi git:(stand_alone_npm_pkg) ✗ sudo npm uninstall -g vedi
removed 1 package in 0.057s
➜  vedi git:(stand_alone_npm_pkg) ✗ 
```

@123aswin123

**Pull request merged**
